In [9]:
import numpy as np

d = 4

In [15]:
J = 1 * np.eye(d) + np.diag([1] * 1 + [0] * (d - 1 - 1), k=1)

In [16]:
J

array([[1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
A = np.tril(np.random.rand(4, 4))
print(np.linalg.inv(A) @ J @ A)

[[ 3.16122258e+00  1.99634727e+00  0.00000000e+00  0.00000000e+00]
 [-2.33971469e+00 -1.16122258e+00  0.00000000e+00  0.00000000e+00]
 [-1.13918945e+00 -1.05228299e+00  1.00000000e+00  0.00000000e+00]
 [ 6.41083311e-01  5.92176358e-01 -1.51309907e-17  1.00000000e+00]]


In [7]:
X = Q.transpose() @ J @ Q

In [12]:
import scipy

T, _ = scipy.linalg.schur(X)

In [16]:
from jordanutils import *

norms = [
    np.linalg.norm(generate_matrix(5, 4, "random", schur=False)) for _ in range(1000)
]

max(norms), min(norms), sum(norms) / len(norms)

(np.float64(7955.8589959728115),
 np.float64(3.440121331211515),
 np.float64(42.00998315408612))

In [15]:
np.linalg.norm(X, ord="fro")

np.float64(84.37097337578993)

In [18]:
J, P = A_sp.jordan_form()

NameError: name 'A_sp' is not defined

In [22]:
import scipy

In [8]:
import numpy as np

A = np.random.rand(5, 5)
Q, R = np.linalg.qr(A)

for i in range(5):
    print(np.linalg.norm(Q[i, :]))

0.9999999999999998
1.0
0.9999999999999999
0.9999999999999999
1.0
